# .graphclientrc.yml
sources:
  - name: superchainsmartaccounts
    handler:
      graphql:
        # endpoint: https://gateway.thegraph.com/api/c6403f4080a355c720e7c7df9cb74917/subgraphs/id/A8Hs1ciwnqsdR8owyFZ77GM5PEXpQBqUTEUpNcnUS6xt
documents:
  - ./src/graphql/get-user-badges.gql